<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>preview</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>

        <!-- Nuget package metadata -->
        <ContinuousIntegrationBuild Condition="'$(ContinuousIntegrationBuild)' == '' and '$(CI)' == 'true'">true</ContinuousIntegrationBuild>
        <Deterministic>true</Deterministic>
        <DebugType>portable</DebugType>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageId>XbfKit</PackageId>
        <Version>0.1.0</Version>
        <Authors>0x5bfa</Authors>
        <Description>Read, decompile, compile, and write versioned XBF documents.</Description>
        <PackageTags>xbf; xaml; decompiler; compiler; reverse-engineering</PackageTags>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/0x5bfa/XbfKit</RepositoryUrl>

    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="" />
        <None Include="..\LICENSE.txt" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>
